name: riskeye
channels:
   - conda-forge
dependencies:
   - python=3.10
   - notebook=7.0.1
   - pip=23.2.1
   - pymc=5.7
   - numpy=1.25.1
   - ipython=8.14
   - matplotlib=3.7.2
   - scipy=1.11.1
   - pytables=3.8
   - pandas=2.0.3
   - pip:
     - pingouin
     - bambi
     - pytables